export default {
	endpoint: 'https://www.binance.com/api/v1/klines',
	logTypes: ['strategy-summary', 'final-strategy-summary'],
	// logTypes: ['enrichment', 'action', 'tick-summary', 'strategy-summary', 'final-strategy-summary']
	initialCapital: 1500,
	maxCandles: 1000,
	numTicksToEvaluate: 90,
	interval: '1d',
	stepSize: 14,

	coins: [
		// 'ATOM',
		// 'BAND',
		'BNB'/*,*/
		// 'BTT',
		// 'KAVA',
		// 'TCT',
		// 'BAT',
		// 'BCH',
		// 'CVC',
		// 'DENT',
		// 'DOGE',
		// 'ETH',
		// 'FUN',
		// 'IOTA',
		// 'LSK',
		// 'NEO',
		// 'REN',
		// 'VITE',
		// 'WIN',
		// 'XMR',
		// 'XRP',
		// 'XTZ',
		// 'ZIL',
		// 'ZRX',
		// 'ADA',
		// 'BTC',
		// 'DUSK',
		// 'LINK',
		// 'MITH',
		// 'NANO',
		// 'NULS',
		// 'OMG',
		// 'ONT',
		// 'QTUM',
		// 'THETA',
		// 'VET',
		// 'XLM'
	]
};